// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/26/2025, 11:54:14 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/gabimaru/Documents/project-internal/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gabimaru/Documents/project-internal/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gabimaru/Documents/project-internal/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gabimaru/Documents/project-internal/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gabimaru/Documents/project-internal/app/plugins/**/*.{js,ts,mjs}","/Users/gabimaru/Documents/project-internal/app/composables/**/*.{js,ts,mjs}","/Users/gabimaru/Documents/project-internal/app/utils/**/*.{js,ts,mjs}","/Users/gabimaru/Documents/project-internal/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gabimaru/Documents/project-internal/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/gabimaru/Documents/project-internal/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/gabimaru/Documents/project-internal/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;